// Entire CLI extension for Pi.
// Auto-generated by `entire enable --agent pi`.
// Do not edit manually. Changes may be overwritten on reinstall.

import type { ExtensionAPI, ExtensionContext } from "@mariozechner/pi-coding-agent";
import { spawnSync } from "node:child_process";

const ENTIRE_CMD = "entire";
const HOOK_TIMEOUT_MS = 30_000;

type RawData = Record<string, unknown>;

type HookPayload = {
 hook_type: string;
 session_id: string;
 session_ref: string;
 timestamp: string;
 cwd: string;
 prompt?: string;
 model?: string;
 raw_data?: RawData;
};

export default function (pi: ExtensionAPI) {
 pi.on("session_start", async (event, ctx) => {
  callEntireHook(ctx, "session-start", {
   raw_data: { reason: event.reason },
  });
 });

 pi.on("before_agent_start", async (event, ctx) => {
  callEntireHook(ctx, "user-prompt-submit", {
   prompt: event.prompt,
  });
 });

 pi.on("agent_end", async (_event, ctx) => {
  callEntireHook(ctx, "stop", {});
 });

 pi.on("session_before_compact", async (_event, ctx) => {
  callEntireHook(ctx, "pre-compact", {});
 });

 pi.on("session_shutdown", async (event, ctx) => {
  if (event.reason !== "quit") return;

  callEntireHook(ctx, "session-end", {
   raw_data: { reason: event.reason },
  });
 });
}

function callEntireHook(
 ctx: ExtensionContext,
 hookName: string,
 fields: Partial<HookPayload>,
): void {
 const payload = buildPayload(ctx, hookName, fields);
 if (!payload) return;

 const hook = hookCommand(hookName);
 spawnSync(hook.command, hook.args, {
  cwd: ctx.cwd,
  input: `${JSON.stringify(payload)}\n`,
  stdio: ["pipe", "ignore", "ignore"],
  timeout: HOOK_TIMEOUT_MS,
 });
}

function buildPayload(
 ctx: ExtensionContext,
 hookName: string,
 fields: Partial<HookPayload>,
): HookPayload | undefined {
 const sessionRef = ctx.sessionManager.getSessionFile();
 if (!sessionRef) return undefined;

 const sessionId = ctx.sessionManager.getSessionId();
 if (!sessionId) return undefined;

 return {
  hook_type: hookName,
  session_id: sessionId,
  session_ref: sessionRef,
  timestamp: new Date().toISOString(),
  cwd: ctx.cwd,
  model: formatModel(ctx),
  ...fields,
  raw_data: {
   leaf_id: ctx.sessionManager.getLeafId(),
   ...(fields.raw_data ?? {}),
  },
 };
}

function formatModel(ctx: ExtensionContext): string | undefined {
 const selectedModel = ctx.model;
 if (!selectedModel) return undefined;

 return `${selectedModel.provider}/${selectedModel.id}`;
}

function hookCommand(hookName: string): { command: string; args: string[] } {
 if (ENTIRE_CMD === "entire") {
  return {
   command: "sh",
   args: [
    "-c",
    `if ! command -v entire >/dev/null 2>&1; then exit 0; fi; exec entire hooks pi ${hookName}`,
   ],
  };
 }

 return {
  command: "sh",
  args: ["-c", `exec ${ENTIRE_CMD} hooks pi ${hookName}`],
 };
}
